### ISSUE TITLE
If RLW is installed in /usr/bin, "Uninstall Roblox" should leave a note that the wrapper itself can only be removed by the package manager

### ISSUE THREAD

**Issue by GLolol** [alfonsojon/roblox-linux-wrapper#101]
tl;dr: "Uninstall Roblox" != "Uninstall Roblox Linux Wrapper".

**Comment by alfonsojon** [comment]
Is there a way to detect if the script is being run from /usr/bin? If so, we can work around this issue by implementing a check.

**Comment by GLolol** [comment]
Yeah, I plan to implement that sometime soon.

**Comment by alfonsojon** [comment]
Alright, thanks. I really appreciate all the work you have done for the Roblox Linux wrapper, it's been such a help to me!

**Comment by GLolol** [comment]
No problem :)

**Comment by alfonsojon** [comment]
Do you have a PayPal/Google Wallet/<insert payment method here> for donations?

**Comment by GLolol** [comment]
Haha, I don't think I'm old enough to own an account yet. :P

**Comment by alfonsojon** [comment]
Ah, I see. I'd gladly add it to the README.md if you did!

**Comment by NokiaGuy** [comment]
@GLolol Not old enough? Here I have a legal PayPal (student account) and I am 16. Laws might be different for you I guess.
