### ISSUE TITLE
Roblox Linux wrapper Black Screen

### ISSUE THREAD

**Issue by Shermanlion6** [alfonsojon/roblox-linux-wrapper#104]
WHen i tried to play roblox after i installed roblox linux wrapper and all i tried to play a game so i press play and then the screen went black and i had to restart my laptop Plz help me how to fix this.

**Comment by GLolol** [comment]
Please be more specific:

- What is causing a black screen? Launching a game via Firefox or ...?
- What version of Wine are you using? Run `wine --version` in a terminal and paste the output here.
- What graphics card and graphics card driver are you using?

**Comment by Shermanlion6** [comment]
I used the method they showed me on
http://roblox.wikia.com/wiki/Install_Roblox_on_Linux i did everything
correctly so when i used the Roblox wrapper and clicked play for a game the
screen went black im useing wine 1.7 i think or 1.6 and it launches on its
own firefox.

**Comment by GLolol** [comment]
I realize that article is really, really old. I've pushed some updates (under account Mildlyridiculous), which points installation instructions HERE instead.

> im useing wine 1.7 i think or 1.6 and it launches on its
own firefox.

Run `wine --version` in a terminal and paste the output here.

**Comment by GLolol** [comment]
Closing due to lack of info.

**Comment by Shermanlion6** [comment]
Hey,

I just signed the petition "Donald J. Trump: Justice for sexually abused
immigrant children" and wanted to see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/ntckX4YFyy

Thanks!
Sherman
