### ISSUE TITLE
Firefox crashing a lot on Wine Staging

### ISSUE THREAD

**Issue by NokiaGuy** [alfonsojon/roblox-linux-wrapper#105]
After loading ROBLOX's initial front page, it constantly crashes.

I just upgraded to Kubuntu 15.04 Plasma 5 and this didn't occur before, so most likely system specific. I know when 14.10 was new I had problems with RLW.

Here's a log of the crash (Through the Wine error reporter)
https://gist.github.com/NokiaGuy/3a0ea3c916358a7e0ab1

Here's the terminal during the event (doesn't look like anything important though)
https://gist.github.com/NokiaGuy/84f96b5a4ed0a779d43b

**Comment by GLolol** [comment]
What version of Firefox is this exactly? The latest ESR release is 38.0.1. I can't reproduce this on Wine stable (1.7.41), though it is a lot slower than what I'm used to, probably because of all the ads the page loads... -_-

I might try staging later.

**Comment by NokiaGuy** [comment]
Firefox 38.0.1 is what it says

**Comment by NokiaGuy** [comment]
Is there any point in posting obvious wine-bugs? Is there anything you guys can really do about it?

**Comment by GLolol** [comment]
@NokiaGuy https://github.com/alfonsojon/roblox-linux-wrapper/issues/96#issuecomment-101494274

**Comment by alfonsojon** [comment]
@NokiaGuy Yes - we can work around wine issues.

**Comment by GLolol** [comment]
#115: new meta issue for crashes in Wine.
