### ISSUE TITLE
"Wine closed unsuccessfully" error.

### ISSUE THREAD

**Issue by josephskimber** [alfonsojon/roblox-linux-wrapper#107]
I install everything and it worked great then i got the exit code one did all updates and still comes up with that error or wine closed unsuceesfully.. i feel as though i missed something simple but im new at this

**Comment by Z0MBIE2** [comment]
Have you tried various games? Wine bugs cause some... a lot... sometimes every game to crash.

**Comment by josephskimber** [comment]
so i tried more games and same deal.  i tried #96 and linux mint terminal commands comes back with this....... finnegan@finnegan-NV53A ~ $ $ sudo add-apt-repository ppa:pipelight/stable
$: command not found

**Comment by NokiaGuy** [comment]
@josephskimber You added an extra "$"

Just copy the text part, so run this:

```
sudo add-apt-repository ppa:pipelight/stable
```

**Comment by josephskimber** [comment]
lol i just restarted the computer and now it says no windows program associated with this application and its in the wine list.. smh

**Comment by GLolol** [comment]
You don't need Pipelight for this script.

@josephskimber Can you debug the script by running it in a terminal and pasting the contents [on a pastebin somewhere](http://gist.github.com)? Also, what version of Wine are you using? (run `wine --version` in a terminal to find out)

**Comment by josephskimber** [comment]
1.6.2

**Comment by josephskimber** [comment]
i dont know how to do the debug. Something is going on with the PPA also(W: GPG error: http://packages.overdrive.pw rlw InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F95C4E34F953726C) this comes up when i update

**Comment by alfonsojon** [comment]
Please thoroughly read the installation instructions :)

**Comment by josephskimber** [comment]
thats a broad statement. for wine or roblox? cause im frustrated that everything work before and now it doesnt. and i can read. point me in the right direction please

**Comment by Z0MBIE2** [comment]
Everything. Thoroughly read all instructions.

**Comment by GLolol** [comment]
You're missing the second step:

----

2) Install the repository's PGP key (this will prevent unauthenticated package errors):

```
wget -O /tmp/sub.class1.server.ca.pem https://www.startssl.com/certs/sub.class1.server.ca.pem
wget --ca-certificate=/tmp/sub.class1.server.ca.pem -O - https://secure.overdrive.pw/repo.gpg.key | sudo apt-key add -
```

----

Or if you're super lazy, install the `utopia-keyring` package I just made available in the repository. :)

**Comment by GLolol** [comment]
Also, your version of Wine is too old. For Ubuntu, you'll need to fetch Wine 1.7 from a PPA or somewhere: https://www.winehq.org/download/ubuntu

----
## Alternative Command Line Instructions for Installing Wine:

It is also possible to add the PPA and install via the terminal. This may be useful on Ubuntu flavors and derivatives.

*sudo add-apt-repository ppa:ubuntu-wine/ppa*

Then update APT package information by running '**sudo apt-get update**'. You can now install Wine by typing '**sudo apt-get install wine1.7**'.

If you'd like to browse the PPA manually, [you can visit its Launchpad page.](https://launchpad.net/~ubuntu-wine/+archive/ppa)

**Comment by josephskimber** [comment]
i stopped and backed up like you said and reread everything. i missed a couple steps. i fixed everything. now the funny part is roblox keeps crashing for every game. is that me with the gecko or is it roblox?

**Comment by skullbro** [comment]
@josephskimber no sadly its just the wine people haven't fixed it yet

**Comment by josephskimber** [comment]
I'm noticing now. Thanks. I'll keep checking back.

**Comment by alfonsojon** [comment]
@josephskimber Try running it with wine-staging. Note: You must have the latest version to use wine-staging properly.

**Comment by GLolol** [comment]
I have opened a new meta-issue for ROBLOX crashes at #115. Please post any new info there.
