### ISSUE TITLE
Program Error!

### ISSUE THREAD

**Issue by masterdome** [alfonsojon/roblox-linux-wrapper#114]
I was loading my game when a program box opened up and it said:
The program RobloxPlayerBeta.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience! And other things what I'm trying to say is it doesn't open up plz help!

**Comment by GLolol** [comment]
Please post the information mentioned here: https://github.com/alfonsojon/roblox-linux-wrapper/blob/master/CONTRIBUTING.md#information-needed-in-a-bug-report 

Specifically: Wine version, OS version, and graphics card model/driver used.
