### ISSUE TITLE
Program stuck in dependencies download, in newer versions.

### ISSUE THREAD

**Issue by LucasWolschick** [alfonsojon/roblox-linux-wrapper#13]
Heh, sorry for bugging you so much, but I'm practically a bug-reporter in this repo. This issue is as the following:

The program gets stuck in an infinite loop when downloading dependencies. What it does is show the zenity window, attempt to download the files, then an error occur, and it gets back to the loop. There is no process to kill, and no cancel button in the zenity window.

off-topic: I'm making a GTK++ interface for this

**Comment by alfonsojon** [comment]
@LucasWolschick Does the latest build fix this? Thanks.

**Comment by alfonsojon** [comment]
Closing, assumed fixed with latest revisions.
