### ISSUE TITLE
Roblox Linux Wrapper keeps asking me to install Roblox again?

### ISSUE THREAD

**Issue by ViciousFurry** [alfonsojon/roblox-linux-wrapper#16]
Roblox wouldn't lauch, when I open the Roblox Wrapper it asks me if I want to install when I've already installed. 

( This happened after I updated to the newest RLW )

**Comment by alfonsojon** [comment]
I'll be working on a reworked version of RLW, which should be less buggy and provide better repairs. In the meantime, close Roblox, Firefox, and RLW, then try running this in a terminal:

rm -rf $HOME/.rlw $HOME/.local/share/wineprefixes/Roblox && bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)

After doing that, it should *hopefully* work. Good luck!

**Comment by ViciousFurry** [comment]
Thank you, that worked. :)

**Comment by alfonsojon** [comment]
Glad to hear!
