### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by stormchaser3000** [alfonsojon/roblox-linux-wrapper#17]
./rlw.sh: line 170: conditional binary operator expected
./rlw.sh: line 170: syntax error near $HOME/.local/share/icons/hicolor/512x512/apps/roblox.png' ./rlw.sh: line 170: if [[ -ne $HOME/.local/share/icons/hicolor/512x512/apps/roblox.png ]]; then'

**Comment by cocobuter** [comment]
I am currently havig the same issue and followed all the steps in the last issue conversation and this the same prompt im receiving.

**Comment by HJSR** [comment]
Same for me.

**Comment by alfonsojon** [comment]
Fixing now, sorry!

**Comment by alfonsojon** [comment]
Is this fixed in build 20150112? Be sure to let me know, thanks for the detailed reports everyone!

**Comment by alfonsojon** [comment]
Assuming fixed.
