### ISSUE TITLE
wrapper not installing need help!

### ISSUE THREAD

**Issue by cocobuter** [alfonsojon/roblox-linux-wrapper#18]
I downloaded the wine staging and ran the wrapper, but now its saying this
/dev/fd/63: line 84: /opt/wine-compholio/bin/wine: No such file or directory
/dev/fd/63: line 85: cd: /home/momo/.local/share/wineprefixes/Roblox: No such file or directory
tr: warning: an unescaped backslash at end of string is not portable
/dev/fd/63: line 87: /opt/wine-compholio/bin/wine: No such file or directory
/dev/fd/63: line 89: /opt/wine-compholio/bin/wine: No such file or directory
/dev/fd/63: line 97: /home/momo/.local/share/applications/Roblox.desktop: No such file or directory

**Comment by cocobuter** [comment]
i do not have a wine-compholio directory i have a /opt/wine-staging/bin/wine directory

**Comment by alfonsojon** [comment]
I'll fix this shortly, it sees wine-compholio has become wine-staging. Thank you for the report!

**Comment by alfonsojon** [comment]
Is this fixed in 20150112a?

**Comment by cocobuter** [comment]
Thank you very much i live in a different time zone and just got back to trying it now

**Comment by cocobuter** [comment]
Thanks the wrapper is working great and perfect now thank you very much again for the help and the work you do!

**Comment by cocobuter** [comment]
Okay so i guess something else was wrong as well. As soon as i launch the game the game window comes up then says an unexpected problems occurs and ive even wiped my laptop and done everything over and it wont work still
