### ISSUE TITLE
PATH

### ISSUE THREAD

**Issue by RainboomDash** [alfonsojon/roblox-linux-wrapper#20]
When I select any option in the Roblox Linux Wrapper, my Terminal gives me this message:

wine client error:0: version mismatch 447/459.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?

**Comment by alfonsojon** [comment]
Close everything related to Roblox Linux Wrapper, then open RLW and select "Reset Roblox to Defaults". This should fix it.

**Comment by RainboomDash** [comment]
Now when I click restore to default, it says it's not installed and keeps installing in a loop.

**Comment by alfonsojon** [comment]
RainboomDash: That's no good! Can you log out, log back in, then run this command in a terminal? 

rm -rf $HOME/.local/share/wineprefixes/Roblox $HOME/.rlw && <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)

**Comment by RainboomDash** [comment]
Permission Denied!

**Comment by RainboomDash** [comment]
I think Permission Denied is the act of Bash trying to execute something that isn't marked executable?

**Comment by alfonsojon** [comment]
Strange.... Try this.
sudo chown -hR `whoami`:`whoami` $HOME && sudo rm -rf $HOME/.local/share/wineprefixes/Roblox $HOME/.rlw && <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)

**Comment by alfonsojon** [comment]
that's not right

**Comment by alfonsojon** [comment]
What distribution are you using?

**Comment by RainboomDash** [comment]
Ubuntu 14.10, I had it working a while ago but then I had to purge wine and ever since it stopped.

**Comment by alfonsojon** [comment]
Thats strange

**Comment by RainboomDash** [comment]
I put that command in above, changed whoami to my account name

No response from the Terminal.

**Comment by RainboomDash** [comment]
Hmmm, any more ideas?

**Comment by alfonsojon** [comment]
@RainboomDash I'd let the terminal finish. Is it done yet?

**Comment by RainboomDash** [comment]
I will restart it, I am making some lunch right now so I will update you on that afterwards. (meaning I will start the terminal command again right now)

**Comment by alfonsojon** [comment]
@RainboomDash If it already finished, then it's done. You don't need to run it again.

**Comment by RainboomDash** [comment]
Oh wait one second, when I ran it, I didnt see but it gave me this: bash: /dev/fd/63: Permission denied

**Comment by alfonsojon** [comment]
@RainboomDash I'm sorry to be the bringer of bad news, but I think there is a problem with your installation that is far greater than the scope of what RLW could have done. I would personally check to see if the hard drive is failing if I were you, as it seems you're having permission-based errors that are often found when the hard drive is failing.

**Comment by RainboomDash** [comment]
I have an idea, I will try this on my other account, this account is pretty used and might be a bit off, I will tell you how it goes.

**Comment by alfonsojon** [comment]
@RainboomDash That's also a very good idea.

**Comment by RainboomDash** [comment]
When I load this account, Ubuntu always complains there is an error, so it might be this account.

**Comment by RainboomDash** [comment]
When I first got this computer, my LightDM crashed at login so I had to use Gnome and that may or may not be the reason of RLW failing, I fixed unity on this new account so I am just downloading it all right now.

**Comment by RainboomDash** [comment]
Oh, I think I identified the issue, could it be Wine Compolio? When I was getting it I couldn't get the latest copy so I got a earlier one, I think this might be it because of this terminal response: 
wine client error:0: version mismatch 447/459.

**Comment by alfonsojon** [comment]
@RainboomDash I think I see the issue now. Delete the .wine folder in your home folder, and try again.

**Comment by RainboomDash** [comment]
Update: I am going to reinstall wine, I think the issue is that I updated wine while I had a wine running which made instances of more than 1. I had to run wineserver -k

**Comment by RainboomDash** [comment]
Same idea ^ haha.

**Comment by RainboomDash** [comment]
You see, I don't have a .wine in my home folder, which always made me curious, but I can still use Wine just fine.

**Comment by alfonsojon** [comment]
@RainboomDash That sounds like a probable cause. Good luck!

**Comment by alfonsojon** [comment]
You do have a .wine folder, it's just hidden by default.

**Comment by RainboomDash** [comment]
I found it. ctrl+h

**Comment by alfonsojon** [comment]
Yep.

**Comment by RainboomDash** [comment]
But Terminal cant find it yet I got it to show. I am just purging Wine and getting a fresh copy.

**Comment by alfonsojon** [comment]
ls -a will show it.

**Comment by RainboomDash** [comment]
la -a just gives me a menu in Terminal.

**Comment by RainboomDash** [comment]
I do -ls -a .wine

No such directory

**Comment by alfonsojon** [comment]
Just ls -a

**Comment by alfonsojon** [comment]
That shows all folders, including hidden

**Comment by RainboomDash** [comment]
Deleted all things wine and Roblox, redoing install.

**Comment by RainboomDash** [comment]
Same issue with "Wine server"

**Comment by alfonsojon** [comment]
I think I'll just revert to using stock Wine, and wait for the fixes from wine-staging to trickle down.

**Comment by RainboomDash** [comment]
What is difference does that make?

**Comment by RainboomDash** [comment]
Good news, I am doing it on a root account and I actually see it installing, on the other ones it would instantly install, maybe root/admin access was needed. The other ones only had SUDO access.

**Comment by RainboomDash** [comment]
RobloxPlayer.exe is actually installing, not sure why it didn't work on others.

**Comment by RainboomDash** [comment]
I can launch RLW and it opens the Windows browser.
Lets test games and studio..

**Comment by RainboomDash** [comment]
Hmm, when clicking play it asks to install.

**Comment by RainboomDash** [comment]
Doing it with Legacy joining doesn't seem to work.

**Comment by RainboomDash** [comment]
Terminal while I installed ROBLOX might have had an error, read this log for me? :)



zach@zach-desktop:~$ bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
Roblox Linux Wrapper v20150121-RELEASE
zenity installed, continuing
Executing w_do_call ddr=gdi
Executing load_ddr gdi
Setting Direct3D/DirectDrawRenderer to gdi
Executing winetricks_early_wine regedit C:\windows\Temp\_ddr=gdi\set-wined3d.reg
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x146060, L"RobloxGameUpdater": stub
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x13ce50, L"RobloxGameUpdater": stub
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x1447f8, L"RobloxGameUpdater": stub
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
tr: warning: an unescaped backslash at end of string is not portable
Failed to load DLL 
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:service:SERV_QueryServiceObjectSecurity 0x13f2f0 4 0x33f528 0 0x33f524 - semi-stub
fixme:service:SERV_QueryServiceObjectSecurity 0x13f2f0 4 0x13f2c8 28 0x33f524 - semi-stub
fixme:service:SetServiceObjectSecurity 0x13f2f0 4 0x33f4e8
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
fixme:shell:SHChangeNotify unknown type 00000003
fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
wine: cannot find L"C:\\windows\\system32\\winebrowser.exe"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"

**Comment by RainboomDash** [comment]
New update: Only this account has a .wine

Others I couldn't find a .wine

**Comment by RainboomDash** [comment]
I found the issue, ROBLOX isn't installing to the right place but studio is that is why the NEW version hasn't worked yet

**Comment by RainboomDash** [comment]
I can launch studio but not player.

**Comment by alfonsojon** [comment]
@RainboomDash You need to go to the top left where there's the little lego (in the URL bar) and allow the Roblox plugin.

**Comment by RainboomDash** [comment]
I have done that.

**Comment by alfonsojon** [comment]
Does it crash when you try to launch?

**Comment by alfonsojon** [comment]
If it does, then it is most likely a wine bug, and must be fixed by developers from the wine project.

**Comment by RainboomDash** [comment]
No, when I click "Play" it will just ask for the plugin, even though it's allowed.

**Comment by alfonsojon** [comment]
@RainboomDash There should be a bar on top that asks if you'd like to allow it, click allow and remember.

**Comment by RainboomDash** [comment]
Yeah, I did all of that.

**Comment by alfonsojon** [comment]
I'll need to take a look when I get home.

**Comment by RainboomDash** [comment]
Also, I went into the "Plugins" area of Firefox and made sure it's always allowed/activated.

**Comment by alfonsojon** [comment]
I can't really help further from here, I'm sorry. Currently in class, but I'll be glad to fix the problem in a few hours when I'm home. Thanks for the reports!

**Comment by RainboomDash** [comment]
No problem, thanks for the effort.

**Comment by jreced** [comment]
I can tell you right now, there's a Wine issue. I've been having that problem too.

**Comment by alfonsojon** [comment]
@jreced Thanks for the feedback, it's very helpful as I never have time to actually get on a computer (school, then straight to work, then sleep). I'm going to redesign the script so that it uses separate prefixes for both wine and wine-staging. As a result, the prefixes shouldn't get confused from now on because of mixed wine versions. I'll be sure to commit it when I finish, as it's a fairly significant undertaking.

**Comment by alfonsojon** [comment]
It will be present in $HOME/.local/share/wineprefixes/Roblox (wine) and $HOME/.local/share/wineprefixes/Roblox-staging (wine-staging).

**Comment by alfonsojon** [comment]
Can you try build 20150127-staging? It should take care of these issues.

**Comment by RainboomDash** [comment]
@alfonsojon Check the most recent post about this bug, I put my error there, this one can be closed off.

**Comment by alfonsojon** [comment]
This is fixed in 20150127c-staging. Closed.
