### ISSUE TITLE
Wont Play Game!

### ISSUE THREAD

**Issue by masterdome** [alfonsojon/roblox-linux-wrapper#21]
It Keeps Telling Me That It Needs To Allow And Remember The Plugin And I Already Did I Checked It In The Add on Section Too!!

**Comment by masterdome** [comment]
I Tried Everything Shuting downing My Computer, Deleting Roblox, Setting is Back To Default Settings,Deleting Ubuntu And Getting It Back But None Worked

**Comment by RainboomDash** [comment]
Hey! This is a known bug and I already reported this. Wine and Wine Compolio are broken with Roblox Linux Wrapper currently, Alfonsojon is working on it currently, but his life is filled with his classes, so be patient as we all anticipate a fix.

**Comment by masterdome** [comment]
Ok Thanks for telling me That!

**Comment by alfonsojon** [comment]
@RainboomDash @masterdome Well, I couldn't have worded it better; school and work are definitely getting in the way! I'm going to be working on it during some of my tech classes. I'll be sure to keep you all updated!

**Comment by alfonsojon** [comment]
Please try build 20140127-staging. This should hopefully fix it!

**Comment by RainboomDash** [comment]
test@zach-desktop:~$ '/home/test/Desktop/Roblox Linux/roblox-linux-wrapper-master/rlw.sh' 
/home/test/Desktop/Roblox Linux/roblox-linux-wrapper-master/rlw.sh: line 23: conditional binary operator expected
/home/test/Desktop/Roblox Linux/roblox-linux-wrapper-master/rlw.sh: line 23: syntax error near `zenity`'
/home/test/Desktop/Roblox Linux/roblox-linux-wrapper-master/rlw.sh: line 23: `if [[ -ne `which zenity` && `which wget` ]]; then'


^^^ Happens when doing the bash command and trying to run it from Terminal.

**Comment by masterdome** [comment]
Have You Got WIne-Staging Installed?

**Comment by masterdome** [comment]
Nervermind it dosen't work with that either

**Comment by RainboomDash** [comment]
Make sure to confirm what you say so we don't make this post list ten billion posts long. :+1:

**Comment by masterdome** [comment]
K
RainboomDash

**Comment by alfonsojon** [comment]
Turns out I made an oops in 20150127-staging. Can you try 20150127b-staging? That fixes an error I found. Thanks for the feedback!

**Comment by RainboomDash** [comment]
Testing out the new build now, post will be updated with results and IF there are errors I find.

**Comment by RainboomDash** [comment]
Build error on install.

test@zach-desktop:~$ bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
Roblox Linux Wrapper v20150127b-staging-RELEASE
/dev/fd/63: line 249: warning: here-document at line 116 delimited by end-of-file (wanted `EOF')
/dev/fd/63: line 250: syntax error: unexpected end of file

**Comment by alfonsojon** [comment]
@RainboomDash My bad, that's fixed as well.

**Comment by RainboomDash** [comment]
Oh yeah, now its doing stuff, will keep you updated.

**Comment by RainboomDash** [comment]
Roblox Player works! Studio will be tested now.

**Comment by RainboomDash** [comment]
Studio works, but there is a small black box in the middle of my screen for every window while Studio is open.  
![untitled](https://cloud.githubusercontent.com/assets/10606504/5932371/de42caa2-a671-11e4-8f58-31d83e509463.png)

**Comment by alfonsojon** [comment]
@RainboomDash That's a wine bug with GNOME, try running it under a different session. So far, it's only affected GNOME 3 and Elementary.

**Comment by RainboomDash** [comment]
Unity is a bit bugged with my system currently, I think I fixed it a while back, I will test that out for you.

**Comment by alfonsojon** [comment]
@RainboomDash Thanks. I usually use MATE, so I have no idea what it's like on other environments.

**Comment by alfonsojon** [comment]
Closing, as it seems the main issues have been resolved.
