### ISSUE TITLE
I can't even download it :(

### ISSUE THREAD

**Issue by Backtalkers** [alfonsojon/roblox-linux-wrapper#22]
/dev/fd/63: line 23: conditional binary operator expected
/dev/fd/63: line 23: syntax error near `zenity`'
/dev/fd/63: line 23: `if [[ -ne `which zenity` && `which wget` ]]; then'
I will not reveal my desktop name, could lead to remote desktop.

**Comment by RainboomDash** [comment]
This is a known issue, redirect your issues here:
https://github.com/alfonsojon/roblox-linux-wrapper/issues/21

**Comment by alfonsojon** [comment]
@RainboomDash Thanks for letting him know!
