### ISSUE TITLE
prefix not being created.

### ISSUE THREAD

**Issue by stormchaser3000** [alfonsojon/roblox-linux-wrapper#24]
the wineprefix is not being created when i attempt to make the prefix to install the dependencies and roblox. i have wine-staging installed and wine1.7 installed as well as zenity and wget.

i would show debug data. but that might not give anything useful from what i saw.

**Comment by RainboomDash** [comment]
Try to delete your .wine in your home folder. To view it use Ctrl+h. If that doesnt work, reinstall wine and wine staging.

**Comment by RainboomDash** [comment]
Also, make sure there isn't already a prefix in that name.

**Comment by RainboomDash** [comment]
If the above doesn't work, run terminal with it and show logs.

**Comment by alfonsojon** [comment]
This should be fixed in build 20150130.

**Comment by RainboomDash** [comment]
Confirmed fix, issue should be closed now.
