### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by masterdome** [alfonsojon/roblox-linux-wrapper#25]
The Sound Wont Work When I Play Roblox.

**Comment by RainboomDash** [comment]
Make sure your sound is directed to your headphones

**Comment by masterdome** [comment]
Ok :+1:

**Comment by RainboomDash** [comment]
If that doesn't solve it, make sure another sound program doesn't have control.
Examples: JACK, Pulse Audio, etc.

**Comment by masterdome** [comment]
Noting Does And The Headphones wont work either

**Comment by RainboomDash** [comment]
Do the headphones work outside of Roblox?

**Comment by masterdome** [comment]
Yes

**Comment by RainboomDash** [comment]
What Linux distribution?

**Comment by masterdome** [comment]
Elementary OS Luna

**Comment by RainboomDash** [comment]
Go on your Roblox Linux Wrapper, reset Roblox to default and try.

**Comment by masterdome** [comment]
is wine gecko suppose to be installed because i accidentally deleted it

**Comment by RainboomDash** [comment]
Yes, it's a Wine dependency

**Comment by RainboomDash** [comment]
To do a quick fix do   sudo apt-get install --reinstall wine

**Comment by masterdome** [comment]
Ok

**Comment by masterdome** [comment]
Internet is pretty slow

**Comment by RainboomDash** [comment]
I am a patient person, and I am here to serve the community for all problems and issues anyone has.

**Comment by masterdome** [comment]
I Have It Now

**Comment by RainboomDash** [comment]
Sound?

**Comment by masterdome** [comment]
No Gecko

**Comment by RainboomDash** [comment]
Any differences made?

**Comment by masterdome** [comment]
No Wait I Cant Download Wine Gecko!

**Comment by masterdome** [comment]
Do You Know How To Download It

**Comment by RainboomDash** [comment]
It comes with Wine.

**Comment by masterdome** [comment]
Not For Me

**Comment by masterdome** [comment]
I Searched For Wine Gecko But I Cant Install It

**Comment by RainboomDash** [comment]
Quick research, it won't fix your sound error, I will bring this to the developer.

**Comment by masterdome** [comment]
Ok Thanks Alot Should I Close This Now?

**Comment by RainboomDash** [comment]
I do not have access to that, I will bring him to this post and continue on this.

**Comment by masterdome** [comment]
K

**Comment by masterdome** [comment]
Well Bye!

**Comment by RainboomDash** [comment]
Goodbye, friend.

**Comment by alfonsojon** [comment]
wine-gecko is not needed for sound. This may be an issue with Ubuntu 12.04 (and Elementary OS Luna). I will look into this.

**Comment by RainboomDash** [comment]
Possible find: Roblox isn't recognized unless launched from RLW, maybe since it's not recognized it may not show up in your sound options, thus no sound being output through earphones or whatever.

**Comment by masterdome** [comment]
Ok

**Comment by masterdome** [comment]
Whats RLW?

**Comment by RainboomDash** [comment]
RLW = Roblox Linux Wrapper

**Comment by alfonsojon** [comment]
I'm looking into this.

**Comment by alfonsojon** [comment]
This is a distribution-specific error. Ensure you are updated, and try again. This is unfortunately not fixable on my end, sorry!
