### ISSUE TITLE
Starting Up

### ISSUE THREAD

**Issue by masterdome** [alfonsojon/roblox-linux-wrapper#26]
It Wont Start Up I Just Got Done Updating It.
When I Press "Play Roblox".

**Comment by RainboomDash** [comment]
Confirmed for me as well.

Syntax error?

**Comment by masterdome** [comment]
I dont know

**Comment by alfonsojon** [comment]
I'll look into this, it may have been a Roblox update.

**Comment by RainboomDash** [comment]
I do believe Roblox updated.

**Comment by RainboomDash** [comment]
When I select Studio, I get this error: 


wine: WINEARCH set to win32 but '/home/newuser/.local/share/wineprefixes/Roblox-wine-staging' is a 64-bit installation.
wine: WINEARCH set to win32 but '/home/newuser/.local/share/wineprefixes/Roblox-wine-staging' is a 64-bit installation.

(zenity:24167): Gdk-WARNING **: gdk_window_set_icon_list: icons too large


Roblox Player is:
(zenity:24177): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
tr: warning: an unescaped backslash at end of string is not portable
wine: WINEARCH set to win32 but '/home/newuser/.local/share/wineprefixes/Roblox-wine-staging' is a 64-bit installation.
wine: WINEARCH set to win32 but '/home/newuser/.local/share/wineprefixes/Roblox-wine-staging' is a 64-bit installation.

(zenity:24192): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

**Comment by alfonsojon** [comment]
@RainboomDash Ah, I see what happened. Currently working on build 20150131. Some added good news, this version has automated error detection routines. If the wine prefix doesn't generate, or something goes out of whack, it will present an error in place of failing silently. I also simplified a lot of code, using simple conditionals rather than complex if/then/else statements. I have also found software which automatically parses my shell scripts and points out any syntax errors or suggestions, so the code is much cleaner now!

**Comment by alfonsojon** [comment]
This will be fixed in build 20150131.

**Comment by RainboomDash** [comment]
When will this be released?

**Comment by alfonsojon** [comment]
Some time today, given that it's build 20150131.

**Comment by RainboomDash** [comment]
Thats what I thought.

**Comment by alfonsojon** [comment]
Here's a little snippet to demonstrate what I'm up to:
`# Some internal functions to make wine more useful to the wrapper.
# This allows the wrapper to know what went wrong and where, without excessive code.
# Note: the "r" prefix indicates a function that extends system functionality.

rwine () {
	$WINE "$@"; [[ $? = "0" ]] || { spawndialog error "wine closed unsuccessfully.\nSee terminal for details. (exit code $?)"; exit $?; }
}
rwineboot () {
	$WINEBOOTBIN "$@"; [[ $? = "0" ]] || { spawndialog error "wineboot closed unsuccessfully.\nSee terminal for details. (exit code $?)"; exit $?; }
}
rwineserver () {
	$WINESERVERBIN "$@"; [[ $? = "0" ]] || { spawndialog error "wineserver closed unsuccessfully.\nSee terminal for details. (exit code $?)"; exit $?; }
}
rwget () {
	wget "$1" -O "$2" 2>&1 | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --progress --window-icon="$RBXICON" --title='Downloading' --auto-close --no-cancel --width=450 --height=120; [[ $? = "0" ]] || { spawndialog error "wget download failed. \nSee terminal for details. (exit code $?)"; exit $?; }
}
`

**Comment by alfonsojon** [comment]
```
# Some internal functions to make wine more useful to the wrapper.
# This allows the wrapper to know what went wrong and where, without excessive code.
# Note: the "r" prefix indicates a function that extends system functionality.

rwine () {
	$WINE "$@"; [[ $? = "0" ]] || { spawndialog error "wine closed unsuccessfully.\nSee terminal for details. (exit code $?)"; exit $?; }
}
rwineboot () {
	$WINEBOOTBIN "$@"; [[ $? = "0" ]] || { spawndialog error "wineboot closed unsuccessfully.\nSee terminal for details. (exit code $?)"; exit $?; }
}
rwineserver () {
	$WINESERVERBIN "$@"; [[ $? = "0" ]] || { spawndialog error "wineserver closed unsuccessfully.\nSee terminal for details. (exit code $?)"; exit $?; }
}
rwget () {
	wget "$1" -O "$2" 2>&1 | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --progress --window-icon="$RBXICON" --title='Downloading' --auto-close --no-cancel --width=450 --height=120; [[ $? = "0" ]] || { spawndialog error "wget download failed. \nSee terminal for details. (exit code $?)"; exit $?; }
}
```
Here's a snippet of code. Long story short, it's using these functions instead of actual system apps (rwine --> wine or wine-staging, with GUI for errors). This makes the program self-aware of its own issues, and lets you know what's wrong.

**Comment by alfonsojon** [comment]
Works very well!

**Comment by RainboomDash** [comment]
Sounds good to me

**Comment by alfonsojon** [comment]
20150131 released, should fix this problem.

**Comment by RainboomDash** [comment]
I will do a quick test on it.

**Comment by jreced** [comment]
Already did, "Wine closed unsuccessfully (exit code 1)"

**Comment by RainboomDash** [comment]
Confirmed ^

I believe the prefix checker has an issue.

**Comment by RainboomDash** [comment]
(zenity:6336): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
wine: WINEARCH set to win32 but '/home/test/.local/share/wineprefixes/roblox-wine-staging' is a 64-bit installation.
wine closed unsuccessfully.
See terminal for details. (exit code 1)

(zenity:6350): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

**Comment by alfonsojon** [comment]
I made a patch that should fix this. If not, make sure everything is closed, then reset Roblox to defaults.

**Comment by RainboomDash** [comment]
Works! Issue close.
