### ISSUE TITLE
odd time format error

### ISSUE THREAD

**Issue by stormchaser3000** [alfonsojon/roblox-linux-wrapper#28]
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"

OS: kubuntu 14.10
desktop environment: kde plasma 5
arch: amd64

**Comment by RainboomDash** [comment]
Does this cause RLW to fail when launching Roblox?

**Comment by stormchaser3000** [comment]
this apparently causes some games to crash possibly. the game i was playing that crashed is paintball (fixes) by daxter33

**Comment by stormchaser3000** [comment]
this sould be due to me using kde plasma 5

**Comment by RainboomDash** [comment]
roblox on Linux unstable I don't think that's causing crashes

**Comment by alfonsojon** [comment]
This bug is out of my control, as it is an issue with wine. I will see what I can do about this.
