### ISSUE TITLE
Studio Login

### ISSUE THREAD

**Issue by RainboomDash** [alfonsojon/roblox-linux-wrapper#32]
I can log in to the studio, but when I try to save to ROBLOX it asks me to sign in. Any quick fix for this one?

**Comment by alfonsojon** [comment]
I'm not entirely sure, but let me know if this does anything;
Close everything ROBLOX-related, and then run the following command in a terminal:
```WINEPREFIX=$HOME/.local/share/wineprefixes/roblox-wine-staging winetricks wininet```

Try again after that.

**Comment by alfonsojon** [comment]
I'll take a look.

**Comment by RainboomDash** [comment]
Seems fine now.
