### ISSUE TITLE
roblox keeps crashing when i play different games like laser tag or paintball (fixes)

### ISSUE THREAD

**Issue by stormchaser3000** [alfonsojon/roblox-linux-wrapper#33]
sometimes robloxplayerbeta.exe crashes sometimes. (i will try to locate debug info)

**Comment by stormchaser3000** [comment]
well i will get debug info later

**Comment by alfonsojon** [comment]
I will look into this. Does anything trigger it, or is it random?

**Comment by alfonsojon** [comment]
Duplicate of bug #31.
