### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gtfc47** [alfonsojon/roblox-linux-wrapper#34]
When i past the line into terminal the terminal reads "Missing dependencies! Make sure zenity, wget, wine, and wine-staging are installed.
Gtk-Message: Failed to load module "unity-gtk-module"

**Comment by Gtfc47** [comment]
Paste

**Comment by masterdome** [comment]
@Gtfc47  You need wine and wine-staging installed on your computer

**Comment by Gtfc47** [comment]
Where can I get wine staging @masterdome

**Comment by masterdome** [comment]
@Gtfc47 From https://github.com/wine-compholio/wine-staging/wiki/Installation

**Comment by alfonsojon** [comment]
See here: https://github.com/wine-compholio/wine-staging

**Comment by Gtfc47** [comment]
Thanks guys I got it up and running now @alfonsojon @masterdome
