### ISSUE TITLE
ROBLOX Crash.

### ISSUE THREAD

**Issue by 5shane1** [alfonsojon/roblox-linux-wrapper#35]
Well, I just erased Ubuntu and install Ubuntu MATE Edition. Installed ROBLOX and still getting Crashes. I open Firefox (Under Wine) and I try to load a game, it gives me a white screen and says ROBLOX has crashed. I tried wiping my system over and over, but same the still problem. I had even did "Set ROBLOX to Defaults" or something and still didn't work.

**Comment by jreced** [comment]
alfonsojon already knows about this. Its probably some Wine issue

**Comment by alfonsojon** [comment]
Not enough info provided. What Linux distribution are you using, and what graphics card do you have?

**Comment by 5shane1** [comment]
AMD Graphics and 14.04 MATE...

**Comment by alfonsojon** [comment]
Do you have proprietary drivers installed? If you are not sure, see here:
https://help.ubuntu.com/community/BinaryDriverHowto/ATI

**Comment by alfonsojon** [comment]
Run the following commands, actually.
```
sudo apt-get install fglrx-updates xvba-va-driver libva-glx1 libva-egl1 vainfo
sudo amdconfig --adapter=all --initial
```

**Comment by alfonsojon** [comment]
Following that, reboot, and see if the game works.

**Comment by 5shane1** [comment]
Now I'm getting green lines and ROBLOX used to work with games with a lot of bricks and connecters but now it doesn't. I can join any game with like just a baseplate but can't join games like big games.

**Comment by alfonsojon** [comment]
Green lines?

**Comment by alfonsojon** [comment]
Duplicate of bug #31.
