### ISSUE TITLE
Roblox Black Screen

### ISSUE THREAD

**Issue by autospamfighter** [alfonsojon/roblox-linux-wrapper#37]
When I launch the script, everything works fine in the web browser... However, when I start a game, the Roblox app just blackscreens. I have a NVIDIA Corporation G98M [Quadro NVS 160M] and am running Roblox on non-legacy mode.

**Comment by alfonsojon** [comment]
Do you have the proper graphics drivers installed? How old is the computer?

**Comment by autospamfighter** [comment]
Computer: mid-2008

I have the Xorg drivers at the moment, Wine says my proprietary drivers are broken.

**Comment by alfonsojon** [comment]
@autospamfighter That would be why it's not working. You need to look into that issue with Wine, as it's an issue with your system.

**Comment by RainboomDash** [comment]
What NVIDIA driver do you currently have?
dpkg -l | grep -i nvidia

If a driver isn't working properly maybe remove it and readd it?
sudo apt-get purge nvidia-current
sudo apt-get install nvidia-current

**Comment by RainboomDash** [comment]
I mean, it's just an idea.

**Comment by alfonsojon** [comment]
@RainboomDash Don't blindly suggest users to install drivers that may or may not be compatible with their system please.

**Comment by autospamfighter** [comment]
@RainboomDash I'm using Noveanu drives atm. I'll try my Nvidia drivers later today.

**Comment by alfonsojon** [comment]
Possible duplicate of #31

**Comment by Shermanlion6** [comment]
Same A Black Screen Appears when i press play im on Samsung ChromeBook

**Comment by alfonsojon** [comment]
@Shermanlion6 What Samsung Chromebook are you attempting to play on?

**Comment by Shermanlion6** [comment]
2

**Comment by alfonsojon** [comment]
@Shermanlion6 Can you please open a new issue? This issue is closed, thank you for your cooperation :)
