### ISSUE TITLE
ROBLOX not booting up...

### ISSUE THREAD

**Issue by 5shane1** [alfonsojon/roblox-linux-wrapper#40]
When I click play ROBLOX, it shows the loading box. But after it goes away, it doesn't pop up with anything.

**Comment by 5shane1** [comment]
Bump.

**Comment by alfonsojon** [comment]
Fixing now!

**Comment by 5shane1** [comment]
Thanks.

**Comment by alfonsojon** [comment]
@5shane1: Try the current release.

**Comment by 5shane1** [comment]
Er, I push the wget command and get this,
shane@shane:~$ bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
Roblox Linux Wrapper v20150206-staging
/dev/fd/63: line 133: syntax error near unexpected token `;;'
/dev/fd/63: line 133: `					rwineserver --wait ;;'
...

**Comment by autospamfighter** [comment]
@5shane1 Try now.

**Comment by autospamfighter** [comment]
@alfonsojon I'm reverting the pull request. There are a few syntax bugs.

**Comment by autospamfighter** [comment]
Try
bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)

**Comment by 5shane1** [comment]
bash: /dev/fd/63: Permission denied

**Comment by IdeaIDev** [comment]
ROBLOX is still not starting up on the current release.
But anyways here is the rlw.sh file with the syntax errors fixed.
http://pastebin.com/G2kr3Gcx
Download it and put it on your desktop, then run
bash /home/yourusername/Desktop/rlw.sh
Replace yourusername with your username, of course.

**Comment by autospamfighter** [comment]
1st:
wget -q https://raw.githubusercontent.com/autospamfighter/roblox-linux-wrapper/master/rlw.sh -O /tmp/rlw.sh
Then:
cd /tmp/
chmod +x rlw.sh
Finally,
./rlw.sh

**Comment by eprent** [comment]
Indeed, it isn't working. However I noticed that it still executes.

For instance, if you look in System Monitor it will show the ROBLOXPlayerBeta process and it's using quite a ton of memory.

**Comment by 5shane1** [comment]
Same issue, ROBLOX still doesn't boot the games.

**Comment by alfonsojon** [comment]
@autospamfighter Is it okay if you do not link to your repository from my issues please? I really appreciate the help, but if you have a fix, do kindly open a pull request! Thanks.

**Comment by autospamfighter** [comment]
@alfonsojon Okay
