### ISSUE TITLE
Syntax error with update version 20150206-staging

### ISSUE THREAD

**Issue by Mercury1964** [alfonsojon/roblox-linux-wrapper#42]
Running the new update results in a syntax error:

    Roblox Linux Wrapper v20150206-staging
    /dev/fd/63: line 133: syntax error near unexpected token `;;'
    /dev/fd/63: line 133: `					rwineserver --wait ;;'

This happens when the new version is autoinstalled by  an older version of the wrapper, installed with the "one-line" statement in the README, or downloaded and run directly.

**Comment by autospamfighter** [comment]
@Mercury1964  Will be fixed soon

**Comment by autospamfighter** [comment]
@Mercury1964  Try now.

**Comment by autospamfighter** [comment]
Try 
bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)

**Comment by Mercury1964** [comment]
It works! Thanks!

**Comment by Chickenmax** [comment]
lol i cant install it

**Comment by GLolol** [comment]
@Chickenmax Please refrain from bumping month old issues like that.
