### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by drewgrif** [alfonsojon/roblox-linux-wrapper#45]
drew@drew-ThinkCentre-E93z ~ $ bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
Roblox Linux Wrapper v20150206-staging
/dev/fd/63: line 133: syntax error near unexpected token `;;'
/dev/fd/63: line 133: `					rwineserver --wait ;;'

**Comment by IdeaIDev** [comment]
Download this http://pastebin.com/G2kr3Gcx , put it on your Desktop, and run
bash /home/drew/Desktop/rlw.sh

**Comment by autospamfighter** [comment]
Try
bash <(wget -q https://raw.githubusercontent.com/autospamfighter/roblox-linux-wrapper/master/rlw.sh -O -))

**Comment by alfonsojon** [comment]
Fixed with pull request #44.
