### ISSUE TITLE
Light rendering issue

### ISSUE THREAD

**Issue by eprent** [alfonsojon/roblox-linux-wrapper#46]
Each time I open Studio it is very dark, the light only renders on (usually) a square somewhere far from the center. Aligning the docks (explorer, output, properties, ext.) seems to fix it and all is dandy.

However... SurfaceLights, SpotLights, and PointLights do not render at all. There's no sign of them in Studio.

I haven't been able to test the lighting issue on the game client because it's been broken the past few days, however I am fairly sure it also has the same issues as Studio.

EDIT: After further investigation, each time you re-align something in Studio... It updates the lighting.
For instance if you add a PointLight in a part it would not show, realign something and it renders just fine.

**Just in case** that it's just me, I have a Intel HD onboard ^(sorry) GPU.

**Comment by alfonsojon** [comment]
I'll take a look. Do you have the Intel GPU drivers installed?

**Comment by eprent** [comment]
Yep, just updated them.

**Comment by alfonsojon** [comment]
Did that fix anything?

**Comment by eprent** [comment]
No, I mean as I updated them before writing this.

**Comment by alfonsojon** [comment]
Ah. I'm looking into it now, I'll keep you updated.

**Comment by eprent** [comment]
The newest update fixed it. Both in client and studio.
