### ISSUE TITLE
Joining As A Guest

### ISSUE THREAD

**Issue by iOptimistic** [alfonsojon/roblox-linux-wrapper#47]
I have just installed Ubuntu on my Laptop yesterday. I've been working on making Roblox work for my computer. I have Roblox Launcher, Roblox Studio, some Windows things that installed after I copied and pasted a code into Terminal, and Wine.

The thing that I need help with is, I join as a guest. Every time. I lauch the code, put in the number (The URL does not work, so I put in the code [1234567]), and I join as a guest. I tried opening Studio and logging in, then launching the code, but no use! And I can't even have a dual boot so I can play roblox! I have to have my Windows 8 Gateway laptop right next to my Ubuntu Dell Inspiron.

**Comment by eprent** [comment]
Make sure to click
>Play ROBLOX
**not**
>Play ROBLOX (Legacy Mode)

Basically "Legacy Mode" is the old method of joining games before he got a better working system. If you use the "Play ROBLOX" option it will allow you to login and join a game. :)

**Comment by alfonsojon** [comment]
Open the "Play Roblox" option, then sign in via Firefox. If that does not work, then there is unfortunately nothing I can do about that. I'm trying to work on a better version of the script which allows for more flexibility with playing the game.

**Comment by iOptimistic** [comment]
I can't seem to run executable files from my desktop. It wants me to choose
a program, or it opens in a test file.

**Comment by autospamfighter** [comment]
Did you try

chmod +x rlw.sh 

When you save it on your desktop?

**Comment by alfonsojon** [comment]
This seems to be working fine for me. Can you reproduce this?

**Comment by alfonsojon** [comment]
Closed, should be working.
