### ISSUE TITLE
Not installing properly

### ISSUE THREAD

**Issue by eprent** [alfonsojon/roblox-linux-wrapper#54]
Likely just a personal issue - but when I try to install it returns this error:

    namehere:~$ bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
    Roblox Linux Wrapper v20150319-stable
    fatal: Not a git repository (or any of the parent directories): .git
    fatal: Not a git repository (or any of the parent directories): .git

Ubuntu 14.04 w/ Unity

------------------------------

If I disable Git, it skips the autoupdate cycle and just breaks at 

    Roblox Linux Wrapper v20150319-stable

**Comment by alfonsojon** [comment]
Try this: sudo apt-get install git

**Comment by eprent** [comment]
Returns the same error.

**Comment by alfonsojon** [comment]
I'll take a look, the issue is with the new updater. I'll try to reproduce it.

**Comment by alfonsojon** [comment]
Confirmed, will fix shortly.

**Comment by alfonsojon** [comment]
Releasing a fix shortly.

**Comment by alfonsojon** [comment]
@eprent Should be working now.

**Comment by eprent** [comment]
Yep! The install is working.
