### ISSUE TITLE
not allowing me to play roblox

### ISSUE THREAD

**Issue by racquelL** [alfonsojon/roblox-linux-wrapper#56]
I am unable to play roblox in linux, it has installed however the allow or allow and remember keeps coming up. now its not coming up for me to click on it. this happens everytime i click on play on one of the games. also i get this error message 'wine closed unsuccessfully. See terminal for details. (exit code 1) on the very top of this error message it says, Roblox Linux Wrapper v2015032-... please help!
this is what comes up in my terminal when i try to run it again...
> begin playerwrapper ()
---
find: `./.gnupg': Permission denied
 > begin rwine ()
---
regsvr32: Failed to load DLL '.\.winC:\users\racquel\Local Settings\Application Data\RobloxVersions\version-3a1b3a29e18e4ba7\RobloxProxy.dll
.\.rlw\roblox-wine-staginC:\users\racquel\Local Settings\Application Data\RobloxVersions\version-3a1b3a29e18e4ba7\RobloxProxy.dll'
 > end rwine ()
---
 > begin rwine ()
---
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:process:SetProcessDEPPolicy (1): stub
fixme:msvcrt:__clean_type_info_names_internal (0x28874d4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x118cd0c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x34335c) stub
fixme:msvcrt:__clean_type_info_names_internal (0xba3294) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a9ee0d4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a8c6384) stub
fixme:msvcrt:__clean_type_info_names_internal (0x80cb4c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x10021a9c) stub

**Comment by alfonsojon** [comment]
Is this working in build 20150326?

**Comment by alfonsojon** [comment]
Closed, fixed.
