### ISSUE TITLE
Annoying error

### ISSUE THREAD

**Issue by Triggatomic** [alfonsojon/roblox-linux-wrapper#58]
I am a Linux newbie. I have wine installed but when I enter the command to install roblox it says missing dependencies... Please can I have a fix? cabextract git shasum wget wine wine-staging zenity
does not work.

**Comment by alfonsojon** [comment]
What does it tell you to install?

**Comment by racquelL** [comment]
Hi Alfonsojon, did you see my question? can you help?

**Comment by Triggatomic** [comment]
Nevermind I fixed it but now I have a different problem... it says to allow roblox but I dont see the button to click allow...
And when I try legacy mode it just crashes and says "ROBLOX encountered an  error and needs to close" Idk why this happens please help.
