### ISSUE TITLE
roblox wont play

### ISSUE THREAD

**Issue by racquelL** [alfonsojon/roblox-linux-wrapper#59]
I am so new at this, ok the bellow information is what i copied of my terminal, I realized it had a system32 and the error, my laptop is 64bits could that be the problem for me not able to play roblox? roblox downloaded using your link, it opens when i log in but when i click on play it gives me the prompt to allow or allow and remember. after I click that nothing happens. I click play again and its the same thing, nothing...please help...

racquel@racquel-eMachines-E527 ~ $  bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
Roblox Linux Wrapper v20150320-master
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
> begin wrapper-install ()
---
Cloning into '/home/racquel/.rlw'...
remote: Counting objects: 647, done.
remote: Compressing objects: 100% (42/42), done.
Receiving objects: 100% (647/647), 204.54 KiB | 236.00 KiB/s, done.
remote: Total 647 (delta 25), reused 0 (delta 0), pack-reused 605
Resolving deltas: 100% (404/404), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
 > begin roblox-install ()
---
 > begin rwineboot ()
---
wine: created the configuration directory '/home/racquel/.rlw/roblox-wine-staging'
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69e6d901, context 0x713fa8, init_notify 0, handle 0xfde7d4): stub
fixme:iphlpapi:CancelMibChangeNotify2 (handle (nil)): stub
wine: configuration in '/home/racquel/.rlw/roblox-wine-staging' has been updated.
 > end rwineboot ()
---
 > begin rwinetricks ()
---
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned empty string
------------------------------------------------------
 > end rwinetricks ()
---
 > begin rwineserver ()
---
 > end rwineserver ()
---
 > begin rwget ()
---
 > end rwget ()
---
 > begin rwine ()
---
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x13c920, L"RobloxGameUpdater": stub
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x13c920, L"RobloxGameUpdater": stub
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x1571d8, L"RobloxGameUpdater": stub
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
 > end rwine ()
---
 > begin rwineserver ()
---
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"

**Comment by alfonsojon** [comment]
Try again with 20150326, it should auto update.

**Comment by alfonsojon** [comment]
Closed, fixed.
