### ISSUE TITLE
NEW ANNOYING Error

### ISSUE THREAD

**Issue by Triggatomic** [alfonsojon/roblox-linux-wrapper#60]
Everytime I click play it just says to allow but I can't. 
When I try Legacy mode it crashes.
Help

**Comment by ArtinPerosteck** [comment]
Exact same issue here.

**Comment by Triggatomic** [comment]
Someone help???

**Comment by racquelL** [comment]
ok no one is paying attention to my issues?? why?

**Comment by alfonsojon** [comment]
Duplicate of #56. Also, this should be fixed in 20150326.

**Comment by alfonsojon** [comment]
@racquelL I try my best to support it, but I am not employed by Roblox. This program was made in my free time; I'm in high school and work daily after school. Given my schedule, it's hard to fix an issue the second it is found; however, I aim to get them fixed as soon as possible.

**Comment by racquelL** [comment]
wow ok thank you...I am impressed!

**Comment by alfonsojon** [comment]
@racquelL Thanks!
