### ISSUE TITLE
ROBLOX Studio - Asset loading is not working

### ISSUE THREAD

**Issue by eprent** [alfonsojon/roblox-linux-wrapper#61]
Starting from the latest update, you haven't been able to load any sort of asset (meaning asset, model, player, etc ) and it's basically causing Studio to be unusable.

It's not because of a ROBLOX update - I have tried with a previous version of the script I saved before and Studio runs fine.

**Comment by alfonsojon** [comment]
I'll look into this, thanks for the report.

**Comment by alfonsojon** [comment]
@eprent It seems to be working fine for me, can you still reproduce this?

**Comment by eprent** [comment]
@alfonsojon Sorry about that - It started working the update after I posted this, but yes it's working flawlessly now.
