### ISSUE TITLE
i am getting program error stil

### ISSUE THREAD

**Issue by racquelL** [alfonsojon/roblox-linux-wrapper#62]
it does not give me the allow and allow and remember button anymore...it seemed like it is working but then i got this message...Program Error the program Roblox PlayerBeta.exe has encountered a serious problem and needs to close. We are sorry for rhe inconvenience. This can be caused by a problem or a deficiancy in Wine. You may want to check the Application Database for tips about runing this application

then I got Roblox Linux Wrapper v20150326 wine closed unsuccessfully. see terminal for details. (exit code1) waiting anxiously for your response

**Comment by alfonsojon** [comment]
Open a terminal, and paste the following after closing everything:

```rm -rf ~/.rlw && /usr/bin/env bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)```

**Comment by racquelL** [comment]
i did and I saw the same error as above. would it make a difference if my laptop is a 64 bit? I really need roblox on my laptop....i saw a message in the terminal about the 32 bit....please help..

**Comment by alfonsojon** [comment]
It does not matter if the laptop is 32 bit or 64 bit. I'm looking into the issue, but I can't seem to reproduce it.

**Comment by masterdome** [comment]
It does not work for me either I entered the code and It still said the error

**Comment by GLolol** [comment]
What version of Wine are you using? Try running the following in a terminal:

```
wine --version
```

**Comment by masterdome** [comment]
@GLolol I have wine-1.4.1

**Comment by masterdome** [comment]
I think that version does not work I used the Software Center now I'm trying the terminal command

**Comment by masterdome** [comment]
Now i have 1.7.18 but, it still says that error when I launch a game

**Comment by GLolol** [comment]
Wine 1.7.18 is pretty old (May 2014). The development newest version is 1.7.39, which worked fine for me. Anything older (1.4, 1.6.x, etc.) is probably too old to play the game.

I'm guessing (from the software versions and the "Software Center") that you are on Ubuntu Precise? [The packages there](https://launchpad.net/~ubuntu-wine/+archive/ubuntu/ppa?field.series_filter=precise) seem to be quite outdated, so you may want to update your OS entirely to fetch the newest versions...

**Comment by masterdome** [comment]
k Thanks

**Comment by masterdome** [comment]
Its updating now :)

**Comment by masterdome** [comment]
Would 14.04 be alright

**Comment by GLolol** [comment]
Yes, now you can get the latest Wine following [these instructions](https://www.winehq.org/download/ubuntu).

**Comment by masterdome** [comment]
It works now Thanks

**Comment by alfonsojon** [comment]
Closed, fixed.
