### ISSUE TITLE
In this about Roblox or can i ask for help on other issues with Linux?

### ISSUE THREAD

**Issue by racquelL** [alfonsojon/roblox-linux-wrapper#66]
I am going to try to get help from anyone on this here...i am attempting to install linux on my desktop it does fine until it is trying to install the gurb...it says....unable to install GRUB in /dev/sda
executing 'grub-install /dev/sda'failed. this is a fatal error.

then sorry an error occured and it was not possible to install the  bootloader at the specific location.
choose a different device to install the bootloader on:
/dev/sda
/dev/sda1
continue without a bootloader.
Cancel the isntallation

please help

**Comment by eprent** [comment]
This is only for ROBLOX issues, but just to fix your issue.. On the live disc install this via terminal. It's a recovery system to fix this.


https://help.ubuntu.com/community/Boot-Repair

**Comment by alfonsojon** [comment]
@racquelL Only for Roblox issues, but the link @eprent posted is valid. Good luck!

**Comment by racquelL** [comment]
ok thanks guys it didnt work so i will send the report to the above info. much appreciate your help
