### ISSUE TITLE
Enchancement: Add an option to redirect Wine output to a file

### ISSUE THREAD

**Issue by Gskartwii** [alfonsojon/roblox-linux-wrapper#70]
Often while playing my terminal gets flooded with fixme stuff.
Because of this, I think that there should be an option to redirect both stdout and stderr to a file, or at least give an option for /dev/null.

**Comment by autospamfighter** [comment]
I think this is doable. HOW exactly is anyone's guess. A config file would be confusing, options at install not changeable...

**Comment by GLolol** [comment]
These can be turned off using the WINEDEBUG environment variable. You can set that in your `bashrc` or whatever you use. [Source](http://wiki.winehq.org/FAQ#head-51e2c09a43f0ac997f818617bec098e97170c503)

I'm not sure if we should apply these globally. These fixmes can be useful if anyone wants to debug Wine.

**Comment by Gskartwii** [comment]
Thanks, that was useful. I'm still getting some output from zenity, but that's okay.
