### ISSUE TITLE
as of: 20150412 -- rlw.sh error, roblox.desktop issue

### ISSUE THREAD

**Issue by martywd** [alfonsojon/roblox-linux-wrapper#72]
Using the new instructions I did the 'git clone ...' command which creates the 'roblox-linux-wrapper' directory in root of the users folder, and the 'xdg-desktop-menu...' command which places a 'Roblox...' menu item in 'Games'.  All good so far.  But....

Then click on 'Menu|Games|Roblox...' .  Nothing happens.  So to the issues.

The 'roblox.desktop' file is still referencing '$HOME/.rlw/' for command execution and icon.

When I 'cd' into 'roblox-linux-wrapper' in Terminal and run './rlw.sh' the command fails with the follow error:

marty@xxxxxx ~/roblox-linux-wrapper 
$ ./rlw.sh 
./rlw.sh: line 177: syntax error near unexpected token `;;'

./rlw.sh: line 177: `		playerwrapper; main;;'

.

**Comment by GLolol** [comment]
The `roblox.desktop` is thoroughly broken right now. #69 has some details in the later comments.

**Comment by GLolol** [comment]
The syntax error should be fixed in c64febb.

**Comment by alfonsojon** [comment]
My bad! Fixing now.

**Comment by alfonsojon** [comment]
I'm sorry about this, this was due to an incomplete commit I made. Thanks @GLolol for fixing it.

**Comment by GLolol** [comment]
Fixed by #69. If it still doesn't work, try running `xdg-desktop-menu uninstall --mode user roblox.desktop`, and then the script again.
