### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by iiShadster** [alfonsojon/roblox-linux-wrapper#77]
So roblox launches correctly, I can play the game for a period of time then all of a sudden my screen goes black causing me to restart my computer. This happens everytime I play roblox with the RLW.

**Comment by GLolol** [comment]
Can you give the following details?

* Wine version (run `wine --version` in a terminal to find it)
* OS name and version
* Graphics card model and driver used

**Comment by iiShadster** [comment]
@GLolol Wine Version is 1.7.38

OS Name and Version: Ubuntu 14.04
Graphics card: Intel 965GM x86/MMX/SSE2

**Comment by GLolol** [comment]
There seems to be issues with the Intel graphics card and Wine: see #64.

**Comment by Shermanlion6** [comment]
Same PLZ FIX THIS I HAVENT PLAYED ROLOX IN 2 YEARS!
