### ISSUE TITLE
Studio not uploading

### ISSUE THREAD

**Issue by IdeaIDev** [alfonsojon/roblox-linux-wrapper#79]
"You must log in to perform this action."
I have reinstalled twice, logged out and logged back in several times, tried on different accounts, yet this issue is still present.
http://i.imgur.com/rfzpuhO.png - Error message.
http://i.imgur.com/qvhdryh.png - I am logged in.

**Comment by alfonsojon** [comment]
Odd... I'll be testing this shortly.

**Comment by eprent** [comment]
Works fine for me, might be system specific. @alfonsojon

**Comment by Gskartwii** [comment]
I was having the same problem a few months ago.
It was a SSL handshake error.

**Comment by alfonsojon** [comment]
@Gskartwii Also working fine for me, I'm not able to reproduce this.

**Comment by InvalidInvoke** [comment]
@alfonsojon I'm @IdeaIDev, just made a new account. I'm not really for sure what triggers it. One day it just stopped working correctly; I've completely uninstalled everything related to rlw, and then reinstalled. Everything is working fine now.

**Comment by alfonsojon** [comment]
Alright, wonderful. I'll assume this is fixed, feel free to let me know here if it comes up again.

**Comment by J4yyy12** [comment]
> Alright, wonderful. I'll assume this is fixed, feel free to let me know here if it comes up again.

So, i have this problem aswell. My project is quite big, since i took about an hour of it, Can you please help?, also this hasn't happened before. And i don't have any plugins on.
