### ISSUE TITLE
RLW should be written in Python, not shell.

### ISSUE THREAD

**Issue by alfonsojon** [alfonsojon/roblox-linux-wrapper#8]
RLW should be written in Python. The current implementation that uses a complex shell script combined with zentiy is not optimal, and should be replaced with native code in a more proper programming language which is better suited for this purpose, a good example being Python.

Requirements:
- GUI (similar to current implementation)
- Not malicious
- Easy to use
- Cannot contain proprietary Roblox code, such as RobloxPlayerLauncherBeta.exe!!!

**Comment by alfonsojon** [comment]
I'd like an update, is there anyone who is actively working on this and should be assigned? Thanks.

**Comment by crazykilla15** [comment]
I am still working on this.

Been caught up with school, plus i have exams next week.

**Comment by alfonsojon** [comment]
@crazykilla15 Got it.

**Comment by crazykilla15** [comment]
Exams over, will resume work.

**Comment by alfonsojon** [comment]
Python is no longer a current target, as it will require more work to do the same job.

**Comment by crazykilla15** [comment]
Interesting.
