### ISSUE TITLE
Auto-updater logic is a bit flawed

### ISSUE THREAD

**Issue by GLolol** [alfonsojon/roblox-linux-wrapper#81]
Right now the script calls `git pull` on run, but runs the older version of `rlw.sh` (in memory) instead of hot loading the new one. So the script won't actually be updated unless you quit the script after it updates and restart it.

**Comment by alfonsojon** [comment]
@GLolol Do you know how we can work around this? I can't find the specific code which is causing this issue, it all looks okay to me.

**Comment by GLolol** [comment]
The problem is, simply running `git pull` and then continuing execution of the script just won't work. The files on the hard disk are updated, but the copy that Bash is currently running in memory isn't. There's no simple foolproof way to implement "auto-updating" like this - you may as well have the user run `git pull` themselves!

**Comment by autospamfighter** [comment]
You could have the script somehow terminating after running git pull and restart, but that would lead to other complications.

**Comment by GLolol** [comment]
@autospamfighter That would require a wrapper script over the main script itself, which I'm hesitant to implement since the script is complex enough as it is. Eventually I plan on switching to binary packaging as mentioned in #83.

**Comment by alfonsojon** [comment]
Could it not just exit and prompt the user to relaunch?

**Comment by GLolol** [comment]
It would need to check whether an update is required or not - this isn't reliable... Otherwise, you'd get into an endlessly restart loop

**Comment by alfonsojon** [comment]
If it does remain like this, the apt and rpm repositories need to be implemented quickly.

**Comment by GLolol** [comment]
b178ae56bf9e8c4838ef357a187ebff6ae5b60d3
