### ISSUE TITLE
ROBLOX Studio launcher sometimes freezes and needs to be forced closed

### ISSUE THREAD

**Issue by NokiaGuy** [alfonsojon/roblox-linux-wrapper#82]
Specifications
------------
Ubuntu 14.04
Cinnamon Desktop Environment
Latest Wine version + Latest RLW version

Description
---------------
It basically freezes sometimes and the launcher [gets stuck at this](http://i.imgur.com/JtElt7C.png)
This persists if I reinstall or reboot.

I have to force close it using taskkill or System Monitor. It works successfully most of the time, but this does get annoying after a while.

**Comment by alfonsojon** [comment]
I can confirm this, but I honestly have no idea which component of wine is to blame. By the way, `xkill` is a nifty tool to quickly kill an application - `ALT + F2`, then `xkill`, click the window, and its parent is dead (oh dear...).

**Comment by NokiaGuy** [comment]
I'll look into it, it doesn't happen on a old version of RLW so it must be something new. @alfonsojon

**Comment by NokiaGuy** [comment]
Not sure if you want this closed or not, lol.
