### ISSUE TITLE
Install via PPA or RPM repository, provide .deb binary files

### ISSUE THREAD

**Issue by alfonsojon** [alfonsojon/roblox-linux-wrapper#83]
Title says all, this should probably be available as a system package. This will facilitate releasing stable updates, automatically resolving dependencies, and bundling our own working and tested version of wine. This will greatly reduce the program's complexity, as well as more properly integrate it into the system.

**Comment by alfonsojon** [comment]
@GLolol Let me know if you can shed light on personal package archive creation, I haven't the slightest clue on where to start!

**Comment by alfonsojon** [comment]
If this is implemented as a system application, the following changes will need to be made:
- Remove automatic git updates, as the package manager will handle updates
- Run script from /usr/sbin, instead of user-defined directory
- Install roblox.png as a system-wide icon in /usr/share/icons

**Comment by GLolol** [comment]
Indeed. It should be `/usr/bin`, since `/usr/sbin` is only added to root's `$PATH`. We won't need root for any of our actions anyways.

**Comment by alfonsojon** [comment]
@GLolol I thought /usr/sbin was for scripts. Is there a proper place to put shell scripts?

**Comment by GLolol** [comment]
No, no, no! `/usr/local/bin` is for apps that are installed outside package management. If we're packaging ourselves, we act like a normal app inside `/usr/bin`. This is regardless of language!

**Comment by alfonsojon** [comment]
Oh, I see. My bad!

**Comment by autospamfighter** [comment]
Do you need help with the apt repos?

**Comment by GLolol** [comment]
@autospamfighter I'm open to any contributions. I'll be setting up a new `debian` branch soon, but I've just been really busy lately with schoolwork.

(I host my own APT repository using [aptly](http://aptly.info/) on a server of mine, if that's of any interest. I use stock Debian for my Linux installs, meaning Ubuntu PPAs aren't that reliable for me.)

**Comment by alfonsojon** [comment]
I have a dedicated Linux server that could be used for this purpose

**Comment by GLolol** [comment]
I've uploaded the initial Debianization into the `testing` branch. :)

**Comment by alfonsojon** [comment]
PPA here: https://launchpad.net/~alfonsojon1997/+archive/ubuntu/roblox-linux-wrapper

Now, it's just a matter of building and uploading.

**Comment by GLolol** [comment]
Are you familiar with the building toolchain?

**Comment by GLolol** [comment]
Anyways, first packages are available in my [personal repository](http://packages.overdrive.pw/) now ([.deb download link](http://packages.overdrive.pw/pool/main/r/roblox-linux-wrapper/roblox-linux-wrapper_2015.04.16%2b10%2bg617678a_all.deb)), along with [a bunch of other stuff](http://packages.overdrive.pw/sid_list.html) that I put in there.

sources.list looks like:
`deb http://packages.overdrive.pw/ sid main`

**Comment by alfonsojon** [comment]
@GLolol I'm sure I can figure it out, I'll add it to my PPA later today. As for debian support, the Launchpad repo should still work as well. I'll get working on the RPM and YUM repos later today.

**Comment by autospamfighter** [comment]
@alfonsojon We should also make sure that the packages are available via GItHub... or at least the .deb file download link in the README.

**Comment by GLolol** [comment]
@autospamfighter There, I added a link to the latest packaged version (branch `testing`, which has all updates from `master` atm and the packaging) in the [releases page](https://github.com/alfonsojon/roblox-linux-wrapper/releases).

**Comment by GLolol** [comment]
@alfonsojon Is this ready to be made official? Users can now use Git, .deb, and *maybe* even one-liner wget to install what's in branch testing at the moment. Version detection fails with a `version-unknown` for the last option, but everything else *should* work (though untested).

**Comment by alfonsojon** [comment]
@GLolol: Feel free to upload the .deb as a "release" to the GitHub releases page, as a binary. That way, we can both provide binaries via GitHub, to reduce dependence upon external servers :)

**Comment by GLolol** [comment]
@alfonsojon Done.
