### ISSUE TITLE
Legacy Mode link not properly detecting ID

### ISSUE THREAD

**Issue by NokiaGuy** [alfonsojon/roblox-linux-wrapper#85]
ROBLOX had changed the whole interface (and the link) for the games page.
It now goes:
http://www.roblox.com/games/IdHere/NameHere

It's not properly detecting the game ID. 

-----------------------------------------------------

**Warning**

They are still doing trial tests with it, so it may be on and off.

**Comment by GLolol** [comment]
So in the new format, the URL and the Game ID are the same? Try this patch: [link](https://secure.overdrive.pw/f/rlw-fix-legacy-mode.patch)

**Comment by NokiaGuy** [comment]
@GLolol What do you mean by "URL and the Game ID are the same?" 

The link requires some sort of name to work.
For example,

http://www.roblox.com/games/192800/ < Will not redirect


http://www.roblox.com/games/192800/WhateverNameHere < Will redirect

**Comment by GLolol** [comment]
When I follow the link to any game in a browser, it will show me the game link in the format you supplied. I don't know what format `robloxplayerbeta.exe` takes in its `--id` argument; does sending in the full game URL (what the patch does) allow the game to start?

**Comment by GLolol** [comment]
Oh wait, I see. The text splitting needs some updating.

**Comment by NokiaGuy** [comment]
I'm getting a prompt saying it's not detecting the URL or ID.

**Comment by NokiaGuy** [comment]
@GLolol

**Comment by GLolol** [comment]
Sorry about that. It should *really* be fixed now.

**Comment by NokiaGuy** [comment]
Yep, works great. @GLolol

**Comment by GazbonicAcid** [comment]
It's not working actually, I get "unknown option --id"

**Comment by GLolol** [comment]
I think the newest Roblox client removed that option entirely. In the testing branch, the menu option no longer exists as well.

**Comment by GazbonicAcid** [comment]
Guess I'll have to hope I can get it working under pipe-light
