### ISSUE TITLE
Your graphics driver is too old.

### ISSUE THREAD

**Issue by NikoCodey** [alfonsojon/roblox-linux-wrapper#88]
Your graphics driver is too old for ROBLOX use.

**Comment by NokiaGuy** [comment]
This is actually a limitation from ROBLOX's client, not Wine or RLW.


What graphics driver do you have?

**Comment by alfonsojon** [comment]
...is your graphics too old (or too inadequate)? Odds are, Roblox wouldn't run on the GPU anyways. Be sure to provide info as to what kind of graphics card (or integrated graphics chip) that your system has installed.

**Comment by NikoCodey** [comment]
Hi, thank you for replying! I have took this picture while i was on Windows before installing Ubuntu http://prntscr.com/6w1j7s http://prntscr.com/6w1m5o http://prntscr.com/6w1ma2

**Comment by NikoCodey** [comment]
Okay, so i managed to update the drivers and it works fine, but ROBLOX keeps crashing every 10 secs on Ripull's minigames

**Comment by NikoCodey** [comment]
Now i can't launch ROBLOX at all after reinstalling http://prntscr.com/6wfjr0

**Comment by NokiaGuy** [comment]
@NikoCodey Did you mess with the installation script? It is not finding Mozilla Firefox. You can reinstall via the menu.

**Comment by NikoCodey** [comment]
Fixed it. The Mad Murderer causes the program to become unresponsive.

**Comment by NokiaGuy** [comment]
Please view #64 as it's the same issue, thanks. @NikoCodey

**Comment by GLolol** [comment]
Games not starting is a separate issue.
