### ISSUE TITLE
this doesn't work for me

### ISSUE THREAD

**Issue by skullbro** [alfonsojon/roblox-linux-wrapper#90]
it just says No such file or directory

**Comment by skullbro** [comment]
THAT DOESN'T HELP AT ALL

**Comment by GLolol** [comment]
No such file or directory for what in particular?

**Comment by skullbro** [comment]
i mean when i copied the command and pasted it it didn't work

**Comment by GLolol** [comment]
Yes, but **where exactly** is it failing? Please paste a full log of what you're getting in a terminal, wrapped with two sets of \`\`\` for formatting. Otherwise, I can't help you.

**Comment by skullbro** [comment]
ok the error is when i paste your code  just the whole code it doesn't work
and when i type sudo apt-get git install it still says no such file or
directory

**Comment by GLolol** [comment]
See https://github.com/alfonsojon/roblox-linux-wrapper/issues/92#issuecomment-95360964, it's `apt-get install git`, not `apt-get git install`.
