### ISSUE TITLE
heres the info 

### ISSUE THREAD

**Issue by skullbro** [alfonsojon/roblox-linux-wrapper#92]
ok i scaned your git but it says E: Invalid operation git when i type sudo apt-get and then your code and when i just copy it it says no such file.

**Comment by alfonsojon** [comment]
Did you install git?

**Comment by skullbro** [comment]
wait i had to install git to gegt the thing

**Comment by skullbro** [comment]
oooooohhhhhhhhhhhhhh

**Comment by skullbro** [comment]
how do i install that on linux

**Comment by GLolol** [comment]
`sudo apt-get install git`, if you're on Ubuntu or anything similar.

**Comment by skullbro** [comment]
hmm.. ok thanks james

**Comment by skullbro** [comment]
wait thjen what do i type

**Comment by skullbro** [comment]
i typed what you said then it needs another code whats that

**Comment by NokiaGuy** [comment]
The terminal will ask for your password after that... @skullbro

**Comment by skullbro** [comment]
hmm....  i tried sudo apt-get install git and every code not at once but 1
at a time

**Comment by GLolol** [comment]
I don't understand what you mean.

**Comment by InvalidInvoke** [comment]
As Nokia stated, the terminal is asking for your password.
The thing that you log in with.
You had to create a password during installation; the terminal needs that to continue, enter that when it asks after you run sudo apt-get install git
@skullbro

**Comment by skullbro** [comment]
wait my computer password or my  account password

**Comment by NokiaGuy** [comment]
When you installed Linux it would've asked for a single password. Use that password.

**Comment by GLolol** [comment]
Closing as not a bug.

**Comment by skullbro** [comment]
oh so i typed it wrong ok ill try so i do my github pasdsword right?

**Comment by skullbro** [comment]
oh know i see mny problem it says i need a newer veersion of wine how do i uptdate it

**Comment by GLolol** [comment]
https://www.winehq.org/download/ubuntu

**Comment by skullbro** [comment]
so whats the command to install the wine? i tried sudo apt-get-repository
*ppa:ubuntu-wine/ppa*

**Comment by GLolol** [comment]
From the WineHQ page:

## Alternative Command Line Instructions for Installing Wine:

It is also possible to add the PPA and install via the terminal. This may be useful on Ubuntu flavors and derivatives.

*sudo add-apt-repository ppa:ubuntu-wine/ppa*

Then update APT package information by running '**sudo apt-get update**'. You can now install Wine by typing '**sudo apt-get install wine1.7**'.

----

I cannot see how this is not clear enough. Help us help you.
