### ISSUE TITLE
CRASHING

### ISSUE THREAD

**Issue by skullbro** [alfonsojon/roblox-linux-wrapper#99]
WTF! IT KEEPS SAYING ROBLOX HAS CRASHED AND NEEDS TO QUIT WE'RE SORRY I REALLY WANT TO PLAY IT BUT IT JUST CRASHES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! @alfonsojon

**Comment by NokiaGuy** [comment]
Sorry about that! You can see the details here: #96

**Comment by skullbro** [comment]
thats very ok. maybe we can help you @alfonsojon

**Comment by GLolol** [comment]
I don't even...

**Comment by alfonsojon** [comment]
@GLolol :+1:
